global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'codegreen'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 2s
    metrics_path: '/metrics'
