services:
  grafana:
    container_name: codegreen-grafana
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=codegreen123
    - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    volumes:
    - /home/srajput/codegreen/monitoring/data/grafana:/var/lib/grafana
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --storage.tsdb.retention.time=15d
    - --web.enable-lifecycle
    container_name: codegreen-prometheus
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - /home/srajput/codegreen/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    - /home/srajput/codegreen/monitoring/data/prometheus:/prometheus
version: '3.8'
